version: 2
updates:
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: daily
    time: "23:30"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: twilio
    versions:
    - 6.51.1
    - 6.52.0
    - 6.53.0
    - 6.54.0
    - 6.55.0
    - 6.56.0
  - dependency-name: matplotlib
    versions:
    - 3.3.4
    - 3.4.0
  - dependency-name: pandas
    versions:
    - 1.2.1
    - 1.2.2
    - 1.2.3
  - dependency-name: numpy
    versions:
    - 1.19.5
    - 1.20.0
    - 1.20.1
  - dependency-name: openpyxl
    versions:
    - 3.0.6
- package-ecosystem: pip
  directory: "/EMAPP"
  schedule:
    interval: daily
    time: "23:30"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: matplotlib
    versions:
    - 3.3.4
    - 3.4.0
  - dependency-name: pandas
    versions:
    - 1.2.1
    - 1.2.2
    - 1.2.3
  - dependency-name: numpy
    versions:
    - 1.19.5
    - 1.20.0
    - 1.20.1
  - dependency-name: openpyxl
    versions:
    - 3.0.6
- package-ecosystem: pip
  directory: "/Character Reading"
  schedule:
    interval: daily
    time: "23:30"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: numpy
    versions:
    - 1.19.5
    - 1.20.0
    - 1.20.1
